
title: 这个需要记下来:)

description: 

url: https://sh.chrysoskun.one

permalink: /:year-:month/:title
timezone: Asia/Shanghai

favicon: /assets/img/favicon.ico

#google_analytics: 
disqus_shortname: chrysoskun

feed:
    path: feed.xml

user:
  name: ChrysosKun
  email: 
  pic: https://cdn.jsdelivr.net/gh/chrysoskun/chrysoskun.github.io/assets/img/pik.jpg
  picAlt: "ChrysosKun's blog"
  aboutme: true 
  search: true
  links: false
exclude:
  - README.md
  - LICENSE
  - github
  - .jekyll-cache
defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comment: true   

markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown: kramdown

# Gitalk settings
#comment_gitalk_clientId: 
#comment_gitalk_clientSecret: 
#comment_gitalk_repo: 
#github_username: 

# Filtering Content
show_drafts: null
limit_posts: 0
future:      false
unpublished: false

