
title: 琅琊琊的小窝

description: Non sunt multiplicanda entia sine necessitate

url: https://langyaya.me

permalink: /:year-:month/:title
timezone: Asia/Shanghai

favicon: /assets/img/favicon.ico

#google_analytics: 
disqus_shortname: langyaya

feed:
    path: feed.xml

user:
  name: 琅琊琊
  email: 
  pic: https://cdn.jsdelivr.net/gh/langyaya/langyaya.github.io/assets/img/pik.jpg
  picAlt: "琅琊琊的小窝"
  aboutme: true 
  search: true
  links: true
exclude:
  - README.md
  - LICENSE
  - github
  - .jekyll-cache
defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comment: true   

markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown: kramdown

# Gitalk settings
#comment_gitalk_clientId: 
#comment_gitalk_clientSecret: 
#comment_gitalk_repo: 
#github_username: 

# Filtering Content
show_drafts: null
limit_posts: 0
future:      false
unpublished: false

